version: '3.9'

services:
    url-shortener:
        container_name: url-shortener-c
        image: url-shortener-i
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8082:8081"

        environment:
            - "CONFIG_PATH=config/local.yaml"
            - "HTTP_SERVER_PASSWORD=pass"
        volumes:
            - ./dbfiles/:/usr/url-srt/